(function(){var t=this;this.puddi=function(e){return t.puddi.mew.push(e)},this.puddi.mew=[],puddi(function(e){t._=e})}).call(this);
(function(){var t="".split,e=[].join;puddi(function(){var i;return i=createjs.Sound,this._registerSound=function(n,a){var r;return r=t.call(n,"."),r.pop(),r=e.call(r,"."),i.registerSound(n,r,void 0,"snd/",a)},this._playSound=function(t){return i.loadComplete(t)?i.play(t):void 0}})}).call(this);
(function(){puddi(function(){function t(t){var e=this;Object.defineProperty(this,"$"+t,{get:function(){return function(t){return null!=t?t:0}(e.$.get(t))},set:function(i){var n;n=parseInt(i,10),isNaN(n)?e.$.del(t):e.$.set(t,n)},configurable:!0,enumerable:!0})}function e(t){var e=this;return Object.defineProperty(this,"$"+t,{get:function(){return e.$.get(t)},set:function(i){null!=i?e.$.set(t,i):e.$.del(t)},configurable:!0,enumerable:!0}),this}var i,n,a,r=[];for(this.$=new Barn(localStorage),i=0,a=(n=["xp","lv","hp","xpTime","overloadTime","lv","mp"]).length;a>i;++i)t.call(this,n[i]);for(i=0,a=(n=["xpPassing"]).length;a>i;++i)r.push(e.call(this,n[i]));return r})}).call(this);
(function(){puddi(function(){var t,e,i=this;return this.stage=new createjs.Stage("game"),createjs.Touch.enable(this.stage),t=$.Callbacks("memory unique"),this.tick=function(e){return t.add(e)},e=createjs.Ticker,e.framerate=30,e.timingMode=e.RAF_SYNCHED,e.addEventListener("tick",t.fire),this.tick(function(t){return i.stage.update(t)})})}).call(this);
(function(){puddi(function(){var t,e,i,n,a=this;return t=e=new createjs.Container,t.x=480,t.y=270,this.stage.addChild(e),i=n=new createjs.Bitmap("img/bg/city-water.jpg"),i.regX=640,i.regY=360,e.addChild(n),this.tick(function(){var t,e,i,r;return t=a.$xp,t/=a.lv().xpMax,e=.05*-t+1,i=10*t,i=new createjs.BlurFilter(i,i,1),r=n,r.scaleX=e,r.scaleY=e,r.filters=[i],r.cache(0,0,1280,720),r})})}).call(this);
(function(){puddi(function(){var t,e,i,n,a,r,s,o,u=this;return t=e=new createjs.Sprite(new createjs.SpriteSheet({images:["img/k/0.png","img/k/1.png","img/k/2.png"],frames:{width:368,height:492},animations:{idle:0,alert:1,exclaim:{frames:[2,1,2,1],next:"exclaimAfter"},exclaimAfter:2}})),t.x=69,t.y=49,i=!1,a=$(window),a.on("mousedown touchstart",function(){return i=!0}),a.on("mouseup touchend",function(){return i=!1,n=void 0}),r=0,s=this.stage,s.addChild(e),s.addEventListener("stagemousemove",function(t){var a,s,o;return a=$.now(),i&&a>r&&a>u.$overloadTime?(r=$.now()+50,s=e.globalToLocal(t.stageX,t.stageY),s.hit=e.hitTest(s.x,s.y),(null!=n&&n.hit||s.hit)&&null!=n&&(o=Math.pow(Math.pow(s.x-n.x,2)+Math.pow(s.y-n.y,2),.5),o=Math.ceil(o),u.$xp+=o),n=s):void 0}),o="idle",this.tick(function(){switch(o){case"idle":if(u.$xpPassing)return e.gotoAndPlay(o="exclaim");break;case"exclaim":if(!u.$xpPassing)return e.gotoAndStop(o="idle")}})})}).call(this);
(function(){function t(t,e){var i={}.hasOwnProperty;for(var n in e)i.call(e,n)&&(t[n]=e[n]);return t}function e(t){function e(){}return e.prototype=t,new e}puddi(function(){var i,n,a,r,s,o,u;for(i=[{xpMin:500,xpPass:1e3,xpMax:3e3,hpGoal:3e3,overloadWait:1e3}],a=[],r=0,s=i.length;s>r;++r)o=r,u=i[r],0===o?a.push(u):a.push(t(e(n[o-1]),u));return n=a,this.lv=function(t){return null==t&&(t=this.$lv),n[t]}})}).call(this);
(function(){puddi(function(){var t,e=this;return this._registerSound("xp-fail.wav",{volume:.3}),this._registerSound("xp-pass.wav",{volume:.5}),this._registerSound("xp-overload.wav"),this._registerSound("mp-up.wav",{volume:.5}),this._registerSound("lv-up.wav",{volume:.5}),t=function(t,i){switch(null==t&&(t=e.$xp),null==i&&(i=e.lv()),!1){case!(t<i.xpMin):return-1;case!(t<i.xpPass):return 0;case!(t<i.xpMax):return 1;default:return 2}},this.tick(function(i){var n,a,r,s;if(n=i.timeStamp-e.$xpTime,n=Math.floor(n),!(1>n)){switch(e.$xp-=n,e.$xp>=0||(e.$xp=0),e.$xpTime=i.timeStamp,i.timeStamp>e.$overloadTime?(a=$("#xp"),a.removeClass("bad"),a.text(e.$xp),e.$xpPassing?$("#xp").addClass("good"):$("#xp").removeClass("good")):(r=$("#xp"),r.addClass("bad"),r.removeClass("good"),r.text(function(t){return t.toFixed(1)}(function(t){return t/1e3}(e.$overloadTime-i.timeStamp)))),s=e.lv(),t(e.$xp,s)){case-1:e.$xpPassing&&(e._playSound("xp-fail"),e.$xpPassing=!1);break;case 0:break;case 1:e.$xpPassing||(e._playSound("xp-pass"),e.$xpPassing=!0);break;case 2:i.timeStamp>e.$overloadTime&&(e._playSound("xp-overload"),e.$xpPassing=!1,e.$overloadTime=i.timeStamp+s.overloadWait,e.$xp=0,e.$hp=0)}return e.$xpPassing?e.$hp+=Math.ceil((e.$xp-s.xpMin)*n/(s.xpMax-s.xpMin)):(e.$hp-=Math.ceil((s.xpPass-e.$xp)*n/(s.xpMax-s.xpMin)),e.$hp>=0||(e.$hp=0)),$("#hp").text(e.$hp+"/"+e.lv().hpGoal),e.$hp>=s.hpGoal&&(e._playSound("mp-up"),e.$xpPassing=!1,e.$xp=0,e.$hp=0,e.$mp++,e.$overloadTime=i.timeStamp+5e3),$("#mp").text(e.$mp),$("#lv").text(e.$lv)}})})}).call(this);
(function(){var t,e,i,n,a;for(t={_:this},e=0,a=(n=this.puddi.mew).length;a>e;++e)i=n[e],i.call(t,t)}).call(this);
