(function(){var t=this;this.puddi=function(e){return t.puddi.mew.push(e)},this.puddi.mew=[],puddi(function(e){t._=e})}).call(this);
(function(){var t="".split,e=[].join;puddi(function(){var n;return n=createjs.Sound,this._registerSound=function(i,r){var a;return a=t.call(i,"."),a.pop(),a=e.call(a,"."),n.registerSound(i,a,void 0,"snd/",r)},this._playSound=function(t){return n.loadComplete(t)?n.play(t):void 0}})}).call(this);
(function(){puddi(function(){function t(t){var e=this;Object.defineProperty(this,"$"+t,{get:function(){return function(t){return null!=t?t:0}(e.$.get(t))},set:function(n){var i;i=parseInt(n,10),isNaN(i)?e.$.del(t):e.$.set(t,i)},configurable:!0,enumerable:!0})}function e(t){var e=this;return Object.defineProperty(this,"$"+t,{get:function(){return e.$.get(t)},set:function(n){null!=n?e.$.set(t,n):e.$.del(t)},configurable:!0,enumerable:!0}),this}var n,i,r,a=[];for(this.$=new Barn(localStorage),n=0,r=(i=["xp","lv","hp","xpTime","overloadTime"]).length;r>n;++n)t.call(this,i[n]);for(n=0,r=(i=["xpPassing"]).length;r>n;++n)a.push(e.call(this,i[n]));return a})}).call(this);
(function(){puddi(function(){var t,e,n=this;return this.stage=new createjs.Stage("game"),createjs.Touch.enable(this.stage),t=$.Callbacks("memory unique"),this.tick=function(e){return t.add(e)},e=createjs.Ticker,e.framerate=30,e.timingMode=e.RAF_SYNCHED,e.addEventListener("tick",t.fire),this.tick(function(t){return n.stage.update(t)})})}).call(this);
(function(){puddi(function(){var t,e,n,i,r=this;return t=e=new createjs.Container,t.x=480,t.y=270,this.stage.addChild(e),n=i=new createjs.Bitmap("img/bg/city-water.jpg"),n.regX=640,n.regY=360,e.addChild(i),this.tick(function(){var t,e,n,a;return t=r.$xp,t/=r.lv().xpMax,e=.05*-t+1,n=10*t,n=new createjs.BlurFilter(n,n,1),a=i,a.scaleX=e,a.scaleY=e,a.filters=[n],a.cache(0,0,1280,720),a})})}).call(this);
(function(){puddi(function(){var t,e,n,i,r,a,o,s,u=this;return t=e=new createjs.Sprite(new createjs.SpriteSheet({images:["img/k/0.png","img/k/1.png","img/k/2.png"],frames:{width:368,height:492},animations:{idle:0,alert:1,exclaim:{frames:[2,1,2,1],next:"exclaimAfter"},exclaimAfter:2}})),t.x=69,t.y=49,n=!1,r=$(window),r.on("mousedown touchstart",function(){return n=!0}),r.on("mouseup touchend",function(){return n=!1,i=void 0}),a=0,o=this.stage,o.addChild(e),o.addEventListener("stagemousemove",function(t){var r,o,s;return r=$.now(),n&&r>a&&r>u.$overloadTime?(a=$.now()+50,o=e.globalToLocal(t.stageX,t.stageY),o.hit=e.hitTest(o.x,o.y),(null!=i&&i.hit||o.hit)&&null!=i&&(s=Math.pow(Math.pow(o.x-i.x,2)+Math.pow(o.y-i.y,2),.5),s=Math.ceil(s),u.$xp+=s),i=o):void 0}),s="idle",this.tick(function(){switch(s){case"idle":if(u.$xpPassing)return e.gotoAndPlay(s="exclaim");break;case"exclaim":if(!u.$xpPassing)return e.gotoAndStop(s="idle")}})})}).call(this);
(function(){function t(t,e){var n={}.hasOwnProperty;for(var i in e)n.call(e,i)&&(t[i]=e[i]);return t}function e(t){function e(){}return e.prototype=t,new e}puddi(function(){var n,i,r,a,o,s,u;for(n=[{xpMin:500,xpPass:1e3,xpMax:3e3}],r=[],a=0,o=n.length;o>a;++a)s=a,u=n[a],0===s?r.push(u):r.push(t(e(i[s-1]),u));return i=r,this.lv=function(t){return null==t&&(t=this.$lv),i[t]}})}).call(this);
(function(){puddi(function(){var t,e,n=this;return this._registerSound("xp-fail.wav",{volume:.3}),this._registerSound("xp-pass.wav",{volume:.5}),this._registerSound("xp-overload.wav"),t=function(t){switch(null==t&&(t=n.$xp),!1){case!(t<n.lv().xpMin):return-1;case!(t<n.lv().xpPass):return 0;case!(t<n.lv().xpMax):return 1;default:return 2}},e=this.$xp,this.tick(function(i){var r,a,o;if(r=i.timeStamp-n.$xpTime,r=Math.floor(r),!(1>r)){switch(n.$xp-=r,n.$xp>=0||(n.$xp=0),n.$xpTime=i.timeStamp,i.timeStamp>n.$overloadTime?(a=$("#xp"),a.removeClass("bad"),a.text(n.$xp),n.$xpPassing?$("#xp").addClass("good"):$("#xp").removeClass("good")):(o=$("#xp"),o.addClass("bad"),o.removeClass("good"),o.text(function(t){return t.toFixed(1)}(function(t){return t/1e3}(n.$overloadTime-i.timeStamp)))),t()){case-1:n.$xpPassing&&(n._playSound("xp-fail"),n.$xpPassing=!1);break;case 0:break;case 1:n.$xpPassing||(n._playSound("xp-pass"),n.$xpPassing=!0);break;case 2:i.timeStamp>n.$overloadTime&&(n._playSound("xp-overload"),n.$xpPassing=!1,n.$overloadTime=i.timeStamp+5e3,n.$xp=0)}return e=n.$xp}})})}).call(this);
(function(){var t,e,n,i,r;for(t={_:this},e=0,r=(i=this.puddi.mew).length;r>e;++e)n=i[e],n.call(t,t)}).call(this);
